-- MySQL Script generated by MySQL Workbench
-- Mon Jul  3 14:15:05 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema solvd-airline
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema solvd-airline
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `solvd-airline` DEFAULT CHARACTER SET utf8 ;
USE `solvd-airline` ;

-- -----------------------------------------------------
-- Table `solvd-airline`.`locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solvd-airline`.`locations` (
  `location_id` INT NOT NULL AUTO_INCREMENT,
  `location_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`location_id`),
  UNIQUE INDEX `location_name_UNIQUE` (`location_name` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `solvd-airline`.`airline_routes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solvd-airline`.`airline_routes` (
  `airline_route_id` INT NOT NULL AUTO_INCREMENT,
  `origin_location_id` INT NOT NULL,
  `destination_location_id` INT NOT NULL,
  `distance_miles` INT NOT NULL,
  `price` DOUBLE NOT NULL,
  PRIMARY KEY (`airline_route_id`),
  INDEX `fk_airline_routes_origin_location_idx` (`origin_location_id` ASC),
  INDEX `fk_airline_routes_dest_location_idx` (`destination_location_id` ASC),
  UNIQUE INDEX `uk_airline_routes_origin_dest` (`origin_location_id` ASC, `destination_location_id` ASC),
  CONSTRAINT `fk_airline_routes_origin_location`
    FOREIGN KEY (`origin_location_id`)
    REFERENCES `solvd-airline`.`locations` (`location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_airline_routes_dest_location`
    FOREIGN KEY (`destination_location_id`)
    REFERENCES `solvd-airline`.`locations` (`location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
